version: "3.4"
services:
  client:
    image: ftlab.utu.fi/app-client:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.client
    ports:
      - "8080:8080"
    environment:
      FTL_SOCKET_SERVICE: socketservice:8080
      FTL_AUTH_SERVICE: authservice:8080
      FTL_NODE_SERVICE: nodeservice:8080
    depends_on:
      - socketservice
      - authservice
    volumes:
      - ./packages/client/dist:/usr/share/nginx/html
  socketservice:
    image: ftlab.utu.fi/app-socketservice:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.services
      target: socketservice
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    volumes:
      - ./:/usr/src/app
  authservice:
    image: ftlab.utu.fi/app-authservice:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.services
      target: authservice
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      MONGO_HOST: authmongo
    volumes:
      - ./:/usr/src/app
  nodeservice:
    image: ftlab.utu.fi/app-nodeservice:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.services
      target: nodeservice
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      MONGO_HOST: authmongo
    volumes:
      - ./:/usr/src/app
  authmongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./.data:/data
    command: redis-server --maxmemory 200mb --save "300 1" --appendonly no
