FROM nginx:latest
COPY ./packages/client/dist /usr/share/nginx/html/
COPY ./packages/client/nginx.conf /etc/nginx/nginx.conf
COPY ./packages/client/reverseproxy.conf /etc/nginx/templates/reverseproxy.conf.template

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
