version: "3.4"
services:
  client:
    image: ftlab.utu.fi/app-client
    ports:
      - "8080:8080"
    environment:
      FTL_STREAM_SERVICE: streamservice:8080
      ASSET_PATH: /lab/
    depends_on:
      - streamservice
  streamservice:
    image: ftlab.utu.fi/app-streamservice
    restart: on-failure
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
  redis:
    image: redis:alpine
    volumes:
      - /media/ftl-data/redis:/data
    command: redis-server --maxmemory 200mb --save "300 1" --appendonly no
#  registry:
#    restart: always
#    image: registry:2
#    ports:
#      - 5000:5000
#    volumes:
#      - /media/ftl-data/docker-registry:/var/lib/registry
