version: "3.4"
services:
  client:
    image: ftlab.utu.fi/app-client
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      FTL_SOCKET_SERVICE: socketservice:8080
      FTL_AUTH_SERVICE: authservice:8080
      FTL_CONFIG_SERVICE: configservice:8080
      FTL_NODE_SERVICE: nodeservice:8080
      FTL_STREAM_SERVICE: streamservice:8080
      ASSET_PATH: /lab/
    depends_on:
      - socketservice
      - authservice
      - configservice
      - nodeservice
      - streamservice
  socketservice:
    image: ftlab.utu.fi/app-socketservice
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
  nodeservice:
    image: ftlab.utu.fi/app-nodeservice
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      MONGO_HOST: authmongo
  streamservice:
    image: ftlab.utu.fi/app-streamservice
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      MONGO_HOST: authmongo
  configservice:
    image: ftlab.utu.fi/app-configservice
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      MONGO_HOST: authmongo
  authservice:
    image: ftlab.utu.fi/app-authservice:${TAG:-latest}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      MONGO_HOST: authmongo
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /srv/ftl/webapp/data/redis:/data
    command: redis-server --maxmemory 200mb --save "300 1" --appendonly no
  authmongo:
    image: mongo:4.2
    restart: unless-stopped
    volumes:
      - /srv/ftl/webapp/data/authmongo:/data/db
    ports:
      - "27017:27017"
  insight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - "8001:8001"
  mongoexpress:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: authmongo
      ME_CONFIG_SITE_BASEURL: /mongo/

#  registry:
#    restart: always
#    image: registry:2
#    ports:
#      - 5000:5000
#    volumes:
#      - /media/ftl-data/docker-registry:/var/lib/registry
